on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_logs:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      deployment_target:
        description: 'Deployment target'
        required: true
        type: choice
        options:
          - web
          - mobile
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_logs }} 
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying to ${environment} environment with log level ${logLevel} for ${deployment_target}."

      - name: Finalize Deployment
        run: echo "Deployment completed successfully."
