name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target deployment environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
      version:
        description: 'Application version to deploy'
        required: true
        type: string
      rollback:
        description: 'True to rollback to a previous version'
        required: false
        type: boolean
      deploy_script:
        description: 'Custom deployment script'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment
        run: echo "Setting up deployment environment: ${{ inputs.environment }}"

      - name: Deploy Application
        run: |
          if [[ "${{ inputs.rollback }}" == "true" ]]; then
            echo "Rolling back to previous version."
            # Add rollback logic here
          else
            echo "Deploying version: ${{ inputs.version }}"
            # Add deployment logic here
          fi

      - name: Custom Deployment Script
        if: ${{ inputs.deploy_script }}
        run: |
          echo "Running custom deployment script:"
          echo "${{ inputs.deploy_script }}"
